# -*- coding: utf-8 -*-
"""
Created on Thu Nov 30 23:01:20 2017

@author: mike
"""

import pickle

name_map={
"The University of Alabama": "Alabama",
"Florida State University": "Florida State",
"Auburn University": "Auburn",
"University of Notre Dame": "Notre Dame",
"University of Georgia": "Georgia",
"Ohio State University-Main Campus": "Ohio State",
"University of Michigan-Ann Arbor": "Michigan",
"Pennsylvania State University-Main Campus": "Penn State",
"University of Oklahoma-Norman Campus": "Oklahoma",
"Clemson University": "Clemson",
"University of Arkansas": "Arkansas",
"Texas Christian University": "Texas Christian",
"University of Florida": "Florida",
"Michigan State University": "Michigan State",
"University of Washington-Seattle Campus": "Washington",
"University of Southern California": "Southern California",
"Virginia Polytechnic Institute and State University": "Virginia Tech",
"University of Wisconsin-Madison": "Wisconsin",
"Louisiana State University and Agricultural & Mechanical College": "Louisiana State",
"The University of Texas at Austin": "Texas",
"University of Iowa": "Iowa",
"University of South Carolina-Columbia": "South Carolina",
"Texas A & M University-College Station": "Texas A&M",
"Baylor University": "Baylor",
"University of Mississippi": "Mississippi",
"University of Miami": "Miami (Florida)",
"The University of Tennessee-Knoxville": "Tennessee",
"University of Nebraska-Lincoln": "Nebraska",
"University of California-Los Angeles": "UCLA",
"Arizona State University-Tempe": "Arizona State",
"University of Minnesota-Twin Cities": "Minnesota",
"Rutgers University-New Brunswick": "Rutgers",
"Northwestern University": "Northwestern",
"Indiana University-Bloomington": "Indiana",
"University of Oregon": "Oregon",
"Stanford University": "Stanford",
"Duke University": "Duke",
"University of North Carolina at Chapel Hill": "North Carolina",
"University of Louisville": "Louisville",
"Syracuse University": "Syracuse",
"University of Pittsburgh-Pittsburgh Campus": "Pittsburgh",
"Iowa State University": "Iowa State",
"Mississippi State University": "Mississippi State",
"University of Kentucky": "Kentucky",
"Vanderbilt University": "Vanderbilt",
"University of California-Berkeley": "California",
"University of Utah": "Utah",
"University of Arizona": "Arizona",
"Boston College": "Boston College",
"University of Missouri-Columbia": "Missouri",
"University of Maryland-College Park": "Maryland",
"University of Virginia-Main Campus": "Virginia",
"Oklahoma State University-Main Campus": "Oklahoma State",
"University of Central Florida": "Central Florida",
"North Carolina State University at Raleigh": "North Carolina State",
"Temple University": "Temple",
"West Virginia University": "West Virginia",
"Washington State University": "Washington State",
"University of Colorado Boulder": "Colorado",
"Kansas State University": "Kansas State",
"University of Illinois at Urbana-Champaign": "Illinois",
"Texas Tech University": "Texas Tech",
"Georgia Institute of Technology-Main Campus": "Georgia Tech",
"Southern Methodist University": "Southern Methodist",
"Purdue University-Main Campus": "Purdue",
"University of Connecticut": "Connecticut",
"Brigham Young University-Provo": "Brigham Young",
"Wake Forest University": "Wake Forest",
"University of Houston": "Houston",
"Oregon State University": "Oregon State",
"University of Memphis": "Memphis",
"San Diego State University": "San Diego State",
"University of Kansas": "Kansas",
"University of Cincinnati-Main Campus": "Cincinnati",
"Colorado State University-Fort Collins": "Colorado State",
"University of Tulsa": "Tulsa",
"University of South Florida-Main Campus": "South Florida",
"Tulane University of Louisiana": "Tulane",
"University of Hawaii at Manoa": "Hawaii",
"Rice University": "Rice",
"East Carolina University": "East Carolina",
"California State University-Fresno": "Fresno State",
"Middle Tennessee State University": "Middle Tennessee State",
"Boise State University": "Boise State",
"Old Dominion University": "Old Dominion",
"University of Nevada-Las Vegas": "Nevada-Las Vegas",
"University of South Alabama": "South Alabama",
"University of Toledo": "Toledo",
"University of Wyoming": "Wyoming",
"The University of Texas at El Paso": "Texas-El Paso",
"Northern Illinois University": "Northern Illinois",
"University of New Mexico-Main Campus": "New Mexico",
"Ohio University-Main Campus": "Ohio",
"Marshall University": "Marshall",
"The University of Texas at San Antonio": "Texas-San Antonio",
"University of Southern Mississippi": "Southern Mississippi",
"Western Michigan University": "Western Michigan",
"University of Massachusetts-Amherst": "Massachusetts",
"University of North Texas": "North Texas",
"University of North Carolina at Charlotte": "Charlotte",
"Utah State University": "Utah State",
"San Jose State University": "San Jose State",
"Florida Atlantic University": "Florida Atlantic",
"Western Kentucky University": "Western Kentucky",
"Miami University-Oxford": "Miami-Ohio",
"University of Nevada-Reno": "Nevada",
"University at Buffalo": "Buffalo",
"University of Akron Main Campus": "Akron",
"Texas State University": "Texas State",
"Louisiana Tech University": "Louisiana Tech",
"University of Louisiana at Lafayette": "Louisiana-Lafayette",
"Florida International University": "Florida International",
"Eastern Michigan University": "Eastern Michigan",
"Ball State University": "Ball State",
"New Mexico State University-Main Campus": "New Mexico State",
"Arkansas State University-Main Campus": "Arkansas State",
"Bowling Green State University-Main Campus": "Bowling Green State",
"Appalachian State University": "Appalachian State",
"University of Idaho": "Idaho",
"Central Michigan University": "Central Michigan",
"Georgia Southern University":"Georgia Southern",
"Georgia State University": "Georgia State",
"Kent State University at Kent":"Kent",
"Troy University":"Troy",
"University of Louisiana at Monroe":"Louisiana-Monroe",
"Coastal Carolina University":"Coastal Carolina",
"University of Alabama at Birmingham":"Alabama-Birmingham",
"United States Air Force Academy":"Air Force",
"United States Military Academy":"Army",
"United States Naval Academy":"Navy"
}

f=open('name_map.pkl','wb')
pickle.dump(name_map,f)
f.close()
